from enum import Enum
from scripts.shared.constants.base import Base

class MainStageImg(Base):
    TEXT = "main_stage/text.png"
    BTN = "main_stage/btn.png"
    NEXT_FEATURE = "main_stage/settlement/next_feature_text.png"
    PRE_START_TEXT = "main_stage/preperation_page/text.png"
    JAMES_FRIEND = "james_friend_icon.png"
    STAGE_SELECTOR = "main_stage_selector.png"
    STAGE_NAV_1 = "main_stage/finder/nav/stage1.png"
    STAGE_NAV_100 = "main_stage/finder/nav/stage100.png"
    STAGE_NAV_200 = "main_stage/finder/nav/stage200.png"
    STAGE_NAV_300 = "main_stage/finder/nav/stage300.png"
    STAGE_NAV_400 = "main_stage/finder/nav/stage400.png"
    MUTIPLIER_LOW_OFF_TEXT = "main_stage/preperation_page/multiplier/dark_low_text.png"
    MUTIPLIER_LOW_ON_TEXT = "main_stage/preperation_page/multiplier/light_low_text.png"
    MULTIPLIER_LOW_BTN = "main_stage/preperation_page/multiplier/low_times_{times}.png"
    MULTIPLIER_HIGH_BTN = "main_stage/preperation_page/multiplier/high_times_{times}.png"
    TEAM_BTN_LOW = "main_stage/preperation_page/team/low_btn.png"
    TEAM_BTN_HIGH = "main_stage/preperation_page/team/high_btn.png"
    TEAM_NUM_LOW_OFF = "main_stage/preperation_page/team/low_num_off_{num}.png"
    TEAM_NUM_LOW_ON = "main_stage/preperation_page/team/low_num_on_{num}.png"
    TEAM_NUM_LOW_DEFAULT = "main_stage/preperation_page/team/low_num_default.png"
    TEAM_NUM_HIGH_OFF = "main_stage/preperation_page/team/high_num_off_{num}.png"
    TEAM_NUM_HIGH_ON = "main_stage/preperation_page/team/high_num_on_{num}.png"
    STAGE = "main_stage/finder/normal/stages/{stage}.png"
    STAGE_NUM_DIGIT = "main_stage/preperation_page/stage_num/{digit}.png"
    AUTO_BTN_LOW_OFF = "main_stage/preperation_page/auto_btn/low_off.png"
    AUTO_BTN_HIGH_OFF = "main_stage/preperation_page/auto_btn/high_off.png"
    AUTO_BTN_LOW_ON = "main_stage/preperation_page/auto_btn/low_on.png"
    AUTO_BTN_HIGH_ON = "main_stage/preperation_page/auto_btn/high_on.png"
    NORMAL_NAV = "main_stage/finder/normal/btn.png"
    HARD_NAV = "main_stage_hard_nav.png"
    METEOR_TEXT = "main_stage_stage_1_meteor_text.png"
    SETTLEMENT = "main_stage/settlement/edge.png"
    PREPERATION_PAGE_BG_LOW = "main_stage/preperation_page/bg/low.png"
    PREPERATION_PAGE_BG_HIGH = "main_stage/preperation_page/bg/high.png"
    CYCLE_HIGH = "main_stage/preperation_page/cycle/high_off.png"
    CYCLE_LOW = "main_stage/preperation_page/cycle/low_off.png"

class MainStageSettlementImg(Base):
    AGAIN = "main_stage/settlement/again_btn.png"
    NEXT = "main_stage/settlement/next_btn.png"

class Stages(str, Enum):
    NEW_COMMON = "main_stage/finder/normal/new_stage/common.png"
    NEW_EVENT = "main_stage/finder/normal/new_stage/event.png"
    NEW_SHINE = "main_stage/finder/normal/new_stage/shine.png" 
    BOSS = "boss_stage.png"

class Treasure(str, Enum):
    ICON = "main_stage/treasure/icon.png"
    ICON2 = "main_stage/treasure/icon2.png"
    TEXT = "main_stage/treasure/text.png"